apiVersion: v1
kind: ReplicationController
metadata:
  name: fake-device
  labels:
    fake-app: device
spec:
  replicas: 1
  selector:
    fake-app: device
  template:
    metadata:
      labels:
        fake-app: device
    spec:
      containers:
      - name: device
        image: ${IMG}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: fake-device-service
  name: iot-device
spec:
  type: NodePort
  ports:
  - port: 3000
    name: port-3000
  selector:
    fake-app: device
