apiVersion: v1
kind: ReplicationController
metadata:
  name: fake-auth-rc
  labels:
    fake-app: auth-server
spec:
  replicas: 1
  selector:
    fake-app: auth-server
  template:
    metadata:
      labels:
        fake-app: auth-server
    spec:
      containers:
      - name: fake-server
        image: ${IMG}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: fake-auth-service
  name: auth-server
spec:
  type: NodePort
  ports:
  - port: 5000
    name: port-5000
  selector:
    fake-app: auth-server
